lab1
vlada967/OOP pull request #1
Opened 2021-09-30 12:22 UTC by vlada967

2021-09-30 17:36 UTC, molo4evan commented
А файлы градла где? Возможно, ты не добавила их в git (в идее файлы красного цвета). Нужен именно gradle проект, а не просто голый Java.

2021-09-30 17:43 UTC, vlada967 commented
> А файлы градла где? Возможно, ты не добавила их в git (в идее файлы красного цвета). Нужен именно gradle проект, а не просто голый Java.

Добавила build.gradle, еще какие-то нужны?

2021-09-30 18:12 UTC, molo4evan requested changes

2021-09-30 18:12 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/task1_1_1/Task_1_1_1/Main.java
> +
Не нужно отделять javadocs от кода, который они документируют

2021-09-30 18:12 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/task1_1_1/Task_1_1_1/Main.java
> +package ru.nsu.fit.oop.task1_1_1.Task_1_1_1;
Не стоит начинать название пакета с заглавной буквы. И, в целом, достаточно одного `task1_1_1` (на мой взгляд, лучше вообще `task111`, но это вкусовщина). Если говорить терминами градла: group - `ru.nsu.fit.oop`, artifact (projectName) - `task1_1_1`

Обычно, как раз, group - название организации (развернутый веб-сайт, как правило) + опционально какой-то глобальный проект, а artifact - это конкретная программа или библиотека, которая реализуется.

2021-09-30 18:12 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/task1_1_1/Task_1_1_1/Main.java
> +    static  void heapify(int arr[], int n, int i) {
`private`

2021-09-30 18:12 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/task1_1_1/Task_1_1_1/Main.java
> +            int tmp = arr[0];
swap встречается в коде дважды, вынеси в метод

2021-09-30 18:12 UTC, molo4evan commented on Task_1_1_1/src/test/java/ru/nsu/fit/oop/task1_1_1/Task_1_1_1/MainTest.java
> +        int output[] = new int[] {1, 2, 3, 4, 5};
1. Не стоит вводить отсортированную версию руками, можно ошибиться. Лучше скопировать и отсортировать стандартными средствами изначальный массив (см. `Arrays`)
2. Тесты однотипные, можно заменить 1 parameterized тестом (см. гайд в гисте)
3. А если передадут `null`?

2021-09-30 18:12 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/task1_1_1/Task_1_1_1/Main.java
> +public class Main {
Если уж это используется, как утилитарный класс (особенно учитывая, что тут нет main метода) - стоит назвать сообразно

2021-10-01 04:53 UTC, molo4evan commented
> 
> 
> > А файлы градла где? Возможно, ты не добавила их в git (в идее файлы красного цвета). Нужен именно gradle проект, а не просто голый Java.
> 
> Добавила build.gradle, еще какие-то нужны?

![изображение](https://user-images.githubusercontent.com/25470436/135567047-20eacc2e-71d6-4036-96f6-4e1b8ef2c4c9.png)
Вот так выглядит структура gradle-проекта. Не только build.gradle, но и скрипты запуска. IDEA генерит ее по дефолту. Если таких файлов в проекте нет - рекомендую скопировать сурсы и пересоздать gradle-проект идеей.

2021-10-01 12:17 UTC, vlada967 commented
Вроде всё исправила

2021-10-01 14:24 UTC, vlada967 commented
> > > А файлы градла где? Возможно, ты не добавила их в git (в идее файлы красного цвета). Нужен именно gradle проект, а не просто голый Java.
> > 
> > 
> > Добавила build.gradle, еще какие-то нужны?
> 
> ![изображение](https://user-images.githubusercontent.com/25470436/135567047-20eacc2e-71d6-4036-96f6-4e1b8ef2c4c9.png) Вот так выглядит структура gradle-проекта. Не только build.gradle, но и скрипты запуска. IDEA генерит ее по дефолту. Если таких файлов в проекте нет - рекомендую скопировать сурсы и пересоздать gradle-проект идеей.

Вроде всё исправила

2021-10-08 05:13 UTC, molo4evan commented on Task_1_1_1/src/test/java/ru/nsu/fit/oop/task1_1_1/HeapSortTest.java
> +    private static Stream<Arguments> SortingArrays() {
1. Методы с маленькой буквы
2. Назови тест и сурс по-разному
3. Ты можешь возвращать не 5 интов, а массив интов, тогда можно тестить массивы разных размеров.
4. empty и oneNumber тоже можно внести в варианты массивов для этого теста (если возвращать массив)

Если поправишь сегодня - зачту как 1.10

2021-10-08 05:14 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/task1_1_1/HeapSort.java
> +        /**
Я не это имел в виду :)
javadocs пишутся до метода, просто пробелом отделять их не надо

2021-10-08 08:48 UTC, merged